In [1]:
import numpy as np

# Solving a System of Linear Equations Using the Elimination Method

The **elimination method**, particularly Gaussian Elimination, is a systematic procedure used to solve systems of linear equations. The goal is to transform the system into a simpler form from which solutions can be easily obtained.

#### Step 1: Forward Elimination to Form an Upper Triangular Matrix

* We start with a system of linear equations, typically represented in matrix form as **Ax = b**, where **A** is the coefficient matrix, **x** is the vector of unknowns, and **b** is the constant vector.
* The process involves converting the matrix **A** into an **upper triangular matrix U**, where all the entries below the main diagonal are zero.
* To achieve this, we **use one variable as a pivot** at a time—starting from the top-left corner of the matrix (the first pivot).
* For each pivot, we **eliminate the corresponding variable** from all equations below by subtracting a suitable multiple of the pivot row from each lower row. This is done so that the entries below the pivot become zero.
* This process is repeated recursively (row by row and column by column) until the matrix is in upper triangular form.

#### Potential Failure: Zero Pivot Elements

* The method can **fail** if any of the pivot elements (diagonal entries of the matrix during elimination) becomes **zero**.
* A zero pivot means we cannot divide by that element to eliminate variables in lower rows, which halts the elimination process.
* To handle this, **row swapping (partial pivoting)** is often used to bring a non-zero pivot to the diagonal position, if possible.

#### Step 2: Backward Substitution

* Once the matrix has been reduced to an upper triangular form **U**, the system **Ux = y** (where y is the transformed right-hand side vector) can be solved using **backward substitution**.
* Starting from the last equation (which contains only one unknown), we solve for that variable.
* We then substitute that value into the equation above to solve for the next variable, and so on, moving upward until all variables are found.


________________________________________________________________

This is a step-by-step example of solving a system of **3 equations with 3 unknowns** using the **elimination method (Gaussian elimination)** with forward elimination and backward substitution:

---

### System of Equations:

$$
\begin{aligned}
1. \quad & x + 2y + 3z = 14 \\
2. \quad & 2x + 5y + 2z = 18 \\
3. \quad & 3x + y + 4z = 20
\end{aligned}
$$

---

### Step 1: Represent the system as an augmented matrix \[A | b]

$$
\begin{bmatrix}
1 & 2 & 3 & | & 14 \\
2 & 5 & 2 & | & 18 \\
3 & 1 & 4 & | & 20 \\
\end{bmatrix}
$$

---

### Step 2: Forward Elimination (convert to upper triangular matrix)

**Pivot: Row 1, element (1,1) = 1**

#### Eliminate x from rows 2 and 3:

* Row2 = Row2 - 2×Row1

$$
[2\ 5\ 2\ |\ 18] - 2×[1\ 2\ 3\ |\ 14] = [0\ 1\ -4\ |\ -10]
$$

* Row3 = Row3 - 3×Row1

$$
[3\ 1\ 4\ |\ 20] - 3×[1\ 2\ 3\ |\ 14] = [0\ -5\ -5\ |\ -22]
$$

Now the matrix looks like:

$$
\begin{bmatrix}
1 & 2 & 3 & | & 14 \\
0 & 1 & -4 & | & -10 \\
0 & -5 & -5 & | & -22 \\
\end{bmatrix}
$$

**Pivot: Row 2, element (2,2) = 1**

#### Eliminate y from row 3:

* Row3 = Row3 + 5×Row2

$$
[0\ -5\ -5\ |\ -22] + 5×[0\ 1\ -4\ |\ -10] = [0\ 0\ -25\ |\ -72]
$$

Now the matrix is upper triangular:

$$
\begin{bmatrix}
1 & 2 & 3 & | & 14 \\
0 & 1 & -4 & | & -10 \\
0 & 0 & -25 & | & -72 \\
\end{bmatrix}
$$

---

### Step 3: Backward Substitution

Start from the bottom:

**From Row 3:**

$$
-25z = -72 \Rightarrow z = \frac{-72}{-25} = 2.88
$$

**From Row 2:**

$$
y - 4z = -10 \Rightarrow y = -10 + 4(2.88) = -10 + 11.52 = 1.52
$$

**From Row 1:**

$$
x + 2y + 3z = 14 \Rightarrow x = 14 - 2(1.52) - 3(2.88) = 14 - 3.04 - 8.64 = 2.32
$$

---

### Final Solution:

$$
x = 2.32,\quad y = 1.52,\quad z = 2.88
$$


In [8]:
# Step 1: Define the augmented matrix [A | b]
A = np.array([
    [1.0, 2.0, 3.0, 14.0],
    [2.0, 5.0, 2.0, 18.0],
    [3.0, 1.0, 4.0, 20.0]
])

n = len(A)


In [9]:
n

3

In [10]:
# Step 2: Forward Elimination
for i in range(n):
    # Make sure the pivot is not zero (optional: implement pivoting here)
    pivot = A[i][i]
    if pivot == 0:
        raise ValueError("Zero pivot encountered!")

    for j in range(i + 1, n):
        ratio = A[j][i] / pivot
        A[j, i:] = A[j, i:] - ratio * A[i, i:]
    print(A)

[[  1.   2.   3.  14.]
 [  0.   1.  -4. -10.]
 [  0.  -5.  -5. -22.]]
[[  1.   2.   3.  14.]
 [  0.   1.  -4. -10.]
 [  0.   0. -25. -72.]]
[[  1.   2.   3.  14.]
 [  0.   1.  -4. -10.]
 [  0.   0. -25. -72.]]


In [4]:
# Step 3: Backward Substitution
x = np.zeros(n)

for i in range(n - 1, -1, -1):
    x[i] = (A[i, -1] - np.dot(A[i, i + 1:n], x[i + 1:n])) / A[i, i]

In [5]:
# Output the solution
print("Solution:")
for i in range(n):
    print(f"x{i+1} = {x[i]:.4f}")

Solution:
x1 = 2.3200
x2 = 1.5200
x3 = 2.8800


- Gaussian elimination can also be viewed through the **lens of matrix operations**, particularly with the use of **elementary matrices** or **elemination matrices**. This perspective is very powerful because it helps us understand what's happening at each step algebraically and allows us to express the entire elimination process as a single matrix multiplication.

---

## 🧮 **Gaussian Elimination Using Elementary Matrices**

### ✅ Definitions

* **Elementary Matrix (E)**: A matrix that represents a single **elementary row operation** (e.g., row swaps, row scaling, or row addition).
* **Upper Triangular Matrix (U)**: A matrix obtained after applying Gaussian elimination to matrix **A**, where all elements below the main diagonal are zero.
* **LU Decomposition**: If we record the row operations using elementary matrices and combine them, we can write:

  $$
  E_k \cdots E_2 E_1 A = U \quad \text{or} \quad U = E A
  $$

  where $E = E_k \cdots E_2 E_1$ is the product of all the elementary matrices.

---

### 🔁 Each Elimination Step as a Matrix Operation

Let’s take the matrix $A$ from your example:

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
2 & 5 & 2 \\
3 & 1 & 4
\end{bmatrix}
$$

Let’s perform Gaussian elimination using **elementary matrices**:

---

### 🔹 **Step 1: Eliminate below (1,1)**

We want to zero out elements below the pivot in the first column.

* To eliminate row 2: subtract $2 \times \text{row}_1$ from row 2.
* To eliminate row 3: subtract $3 \times \text{row}_1$ from row 3.

We define the elementary matrix $E_1$ that does this:

$$
E_1 =
\begin{bmatrix}
1 & 0 & 0 \\
-2 & 1 & 0 \\
-3 & 0 & 1
\end{bmatrix}
$$

Then:

$$
A^{(1)} = E_1 A =
\begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & -4 \\
0 & -5 & -5
\end{bmatrix}
$$

---

### 🔹 **Step 2: Eliminate below (2,2)**

Now eliminate the entry in (3,2) using row 2.

* Add $5 \times \text{row}_2$ to row 3.

Elementary matrix $E_2$:

$$
E_2 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 5 & 1
\end{bmatrix}
$$

Then:

$$
A^{(2)} = E_2 A^{(1)} =
\begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & -4 \\
0 & 0 & -25
\end{bmatrix}
= U
$$

---

### ✅ Final Result: From A to U

We applied two elementary matrices:

$$
U = E_2 E_1 A
$$

Define:

$$
E = E_2 E_1
\Rightarrow U = EA
$$

So instead of applying each step manually, we can **compose the elementary matrices into one transformation** $E$, such that multiplying $E$ by $A$ gives us $U$ in one go.

---

### 💡 Why This Matters

* The product $E$ is invertible, since each elementary matrix is invertible.
* If we want to **keep track of how the system was transformed**, $E$ serves as a complete record.
* In LU decomposition, we often write:

  $$
  A = LU \quad \text{where} \quad L = E^{-1}
  $$

  That is, the inverse of the product of the elimination matrices gives the **lower triangular matrix** used in decomposition.

---

### 🧠 Summary

| Concept                        | Meaning                                         |
| ------------------------------ | ----------------------------------------------- |
| **Elementary matrix**          | Encodes a single row operation                  |
| **Forward elimination**        | Applying a sequence of $E_k, \dots, E_1$ to A   |
| **Upper triangular matrix**    | Result of elimination: $U = EA$                 |
| **Single-step transformation** | Multiply all $E_i$ into one matrix: $E$         |
| **Reversibility**              | $E$ is invertible → useful for LU decomposition |


In [11]:
import numpy as np

# Original matrix A
A = np.array([
    [1.0, 2.0, 3.0],
    [2.0, 5.0, 2.0],
    [3.0, 1.0, 4.0]
])

# Step 1: Create E1 to eliminate entries below A[0, 0]
E1 = np.identity(3)
E1[1, 0] = -2.0  # Row2 - 2×Row1
E1[2, 0] = -3.0  # Row3 - 3×Row1

A1 = E1 @ A  # Apply E1

# Step 2: Create E2 to eliminate entry below A1[1, 1]
E2 = np.identity(3)
E2[2, 1] = 5.0  # Row3 + 5×Row2

U = E2 @ A1  # Apply E2

# Combine E = E2 @ E1
E = E2 @ E1

# Verify U = E @ A
U_check = E @ A

# Print results
np.set_printoptions(precision=2, suppress=True)

print("Original Matrix A:")
print(A)
print("\nElementary Matrix E1:")
print(E1)
print("\nA after applying E1 (A1):")
print(A1)
print("\nElementary Matrix E2:")
print(E2)
print("\nUpper Triangular Matrix U:")
print(U)
print("\nCombined Elementary Matrix E = E2 @ E1:")
print(E)
print("\nVerification: E @ A = U?")
print(U_check)

Original Matrix A:
[[1. 2. 3.]
 [2. 5. 2.]
 [3. 1. 4.]]

Elementary Matrix E1:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-3.  0.  1.]]

A after applying E1 (A1):
[[ 1.  2.  3.]
 [ 0.  1. -4.]
 [ 0. -5. -5.]]

Elementary Matrix E2:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 5. 1.]]

Upper Triangular Matrix U:
[[  1.   2.   3.]
 [  0.   1.  -4.]
 [  0.   0. -25.]]

Combined Elementary Matrix E = E2 @ E1:
[[  1.   0.   0.]
 [ -2.   1.   0.]
 [-13.   5.   1.]]

Verification: E @ A = U?
[[  1.   2.   3.]
 [  0.   1.  -4.]
 [  0.   0. -25.]]


## **permutation matrices**, which are fundamental when working with **row exchanges** (like in partial pivoting) or **column exchanges** (like in QR decomposition or column pivoting in LU with full pivoting).

---

## 🔄 **Permutation Matrices**

### ✅ What Is a Permutation Matrix?

A **permutation matrix** is a square matrix obtained by **reordering the rows or columns** of the identity matrix. It represents a **reordering operation**:

* Multiplying a matrix on the **left** by a permutation matrix swaps **rows**.
* Multiplying a matrix on the **right** by a permutation matrix swaps **columns**.

---

### 🔁 **Swapping Rows Example**

Suppose we want to swap **row 1 and row 2** of the following matrix $A$:

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

#### Row swap permutation matrix $P$:

$$
P =
\begin{bmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

#### Result:

$$
PA =
\begin{bmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
=
\begin{bmatrix}
4 & 5 & 6 \\
1 & 2 & 3 \\
7 & 8 & 9
\end{bmatrix}
$$

✅ Row 1 and 2 are swapped.

---

### 🔁 **Swapping Columns Example**

To swap **columns 1 and 3**, we multiply from the **right** by:

$$
Q =
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{bmatrix}
$$

Then:

$$
AQ =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{bmatrix}
=
\begin{bmatrix}
3 & 2 & 1 \\
6 & 5 & 4 \\
9 & 8 & 7
\end{bmatrix}
$$

✅ Columns 1 and 3 are swapped.

---

## 🧠 Important Properties

* Permutation matrices are **orthogonal**:

  $$
  P^{-1} = P^T
  $$
* They’re used in **partial pivoting** during Gaussian elimination when the pivot is zero or too small:

  $$
  PA = LU
  $$

  where **P** records the row swaps.


---

### 📌 Summary Table

| Operation            | Multiply By | Effect                           |
| -------------------- | ----------- | -------------------------------- |
| Swap rows i and j    | $P \cdot A$ | Rows i and j of A are swapped    |
| Swap columns i and j | $A \cdot P$ | Columns i and j of A are swapped |
| Undo permutation     | $P^T$       | Reverses the swap                |

---

Let me know if you'd like an example using permutation matrices within **LU decomposition with pivoting**!


In [12]:
# Original matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Permutation matrix to swap row 1 and row 2
P_row = np.array([
    [0, 1, 0],
    [1, 0, 0],
    [0, 0, 1]
])

# Permutation matrix to swap column 1 and 3
P_col = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])

# Apply row swap
A_row_swapped = P_row @ A

# Apply column swap
A_col_swapped = A @ P_col

# Print results
print("Original A:\n", A)
print("\nAfter Row Swap (1<->2):\n", A_row_swapped)
print("\nAfter Column Swap (1<->3):\n", A_col_swapped)

Original A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After Row Swap (1<->2):
 [[4 5 6]
 [1 2 3]
 [7 8 9]]

After Column Swap (1<->3):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
