In [1]:
import numpy as np

## Multiplying two matrices can be done in a few different ways depending on the context and what you're trying to compute. 
### Here are **four common methods** to multiply matrices, each with an explanation, example, and rules:

---

### **1. Standard Matrix Multiplication (Dot Product Method)**

**Explanation:**
This is the traditional way of multiplying matrices: each entry in the result is the dot product of a row from the first matrix and a column from the second.

**Rule:**
If matrix **A** is of size `(m × n)` and matrix **B** is of size `(n × p)`, then their product **AB** is defined and will be of size `(m × p)`.

**Example:**

Let
A = $\begin{bmatrix}1 & 2\\ 3 & 4\end{bmatrix}$,
B = $\begin{bmatrix}5 & 6\\ 7 & 8\end{bmatrix}$

AB =

$$
\begin{bmatrix}
(1×5 + 2×7) & (1×6 + 2×8)\\
(3×5 + 4×7) & (3×6 + 4×8)
\end{bmatrix}
=
\begin{bmatrix}
19 & 22\\
43 & 50
\end{bmatrix}
$$

---

### **2. Element-wise Multiplication (Hadamard Product)**

**Explanation:**
Multiply corresponding elements from both matrices. This is *not* standard matrix multiplication, but used in machine learning and image processing.

**Rule:**
Both matrices must be of the same dimension `(m × n)`.

**Example:**

Let
A = $\begin{bmatrix}1 & 2\\ 3 & 4\end{bmatrix}$,
B = $\begin{bmatrix}5 & 6\\ 7 & 8\end{bmatrix}$

Hadamard product A ∘ B =

$$
\begin{bmatrix}
1×5 & 2×6\\
3×7 & 4×8
\end{bmatrix}
=
\begin{bmatrix}
5 & 12\\
21 & 32
\end{bmatrix}
$$

---

### **3. Matrix Multiplication Using Broadcasting (Outer Product)**

**Explanation:**
Used when multiplying a column vector with a row vector to produce a full matrix.

**Rule:**
If **u** is a column vector of size `(m × 1)` and **v** is a row vector of size `(1 × n)`, then **uvᵀ** results in an `(m × n)` matrix.

**Example:**

Let
u = $\begin{bmatrix}1\\2\end{bmatrix}$,
v = $\begin{bmatrix}3 & 4\end{bmatrix}$

uvᵀ =

$$
\begin{bmatrix}
1×3 & 1×4\\
2×3 & 2×4
\end{bmatrix}
=
\begin{bmatrix}
3 & 4\\
6 & 8
\end{bmatrix}
$$

---

### **4. Block Matrix Multiplication**

**Explanation:**
This method partitions large matrices into smaller submatrices ("blocks") and multiplies them using standard matrix multiplication rules.

**Rule:**
Each block must align in size such that the standard multiplication between blocks is valid.

**Example:**

Let
A = $\begin{bmatrix}A_{11} & A_{12}\\ A_{21} & A_{22}\end{bmatrix}$,
B = $\begin{bmatrix}B_{11} & B_{12}\\ B_{21} & B_{22}\end{bmatrix}$

Then
AB =

$$
\begin{bmatrix}
A_{11}B_{11} + A_{12}B_{21} & A_{11}B_{12} + A_{12}B_{22}\\
A_{21}B_{11} + A_{22}B_{21} & A_{21}B_{12} + A_{22}B_{22}
\end{bmatrix}
$$

**Concrete Example:**
Let each block be 1×1 (i.e., scalar):

A = $\begin{bmatrix}1 & 2\\ 3 & 4\end{bmatrix}$,
B = $\begin{bmatrix}5 & 6\\ 7 & 8\end{bmatrix}$

Then this gives the same result as in method 1:

$$
AB = \begin{bmatrix}19 & 22\\ 43 & 50\end{bmatrix}
$$

---

### Summary Table:

| Method                  | Rule for Dimensions      | Operation                             | Use Case                      |
| ----------------------- | ------------------------ | ------------------------------------- | ----------------------------- |
| Standard (Dot Product)  | A(m×n) × B(n×p) → C(m×p) | Row-by-column multiplication          | General matrix algebra        |
| Element-wise (Hadamard) | A(m×n) × B(m×n) → C(m×n) | Multiply corresponding elements       | ML, image processing          |
| Outer Product           | u(m×1) × v(1×n) → C(m×n) | Each element is ui × vj               | Vector expansion, tensor ops  |
| Block Multiplication    | Conformable block sizes  | Matrix blocks multiplied like scalars | Optimized computation, theory |


In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Method 1: Standard matrix multiplication
C = np.dot(A, B)
# or
C = A @ B

print("Standard Matrix Multiplication:\n", C)

Standard Matrix Multiplication:
 [[19 22]
 [43 50]]


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Method 2: Element-wise multiplication
C = A * B

print("Element-wise (Hadamard) Product:\n", C)

Element-wise (Hadamard) Product:
 [[ 5 12]
 [21 32]]


In [4]:
u = np.array([[1], [2]])   # column vector (2×1)
v = np.array([[3, 4]])     # row vector (1×2)

# Method 3: Outer product via broadcasting
C = u @ v  # or np.dot(u, v)

print("Outer Product:\n", C)

Outer Product:
 [[3 4]
 [6 8]]


In [5]:
# Blocks as small matrices
A11 = np.array([[1]])
A12 = np.array([[2]])
A21 = np.array([[3]])
A22 = np.array([[4]])

B11 = np.array([[5]])
B12 = np.array([[6]])
B21 = np.array([[7]])
B22 = np.array([[8]])

# Method 4: Block matrix multiplication manually
C11 = A11 @ B11 + A12 @ B21
C12 = A11 @ B12 + A12 @ B22
C21 = A21 @ B11 + A22 @ B21
C22 = A21 @ B12 + A22 @ B22

# Combine blocks into full matrix
top = np.hstack([C11, C12])
bottom = np.hstack([C21, C22])
C = np.vstack([top, bottom])

print("Block Matrix Multiplication:\n", C)

Block Matrix Multiplication:
 [[19 22]
 [43 50]]


## ✅ **1. Inverse of a Square Matrix**

A **square matrix** $A$ has an **inverse** (denoted $A^{-1}$) **if and only if**:

* $A \cdot A^{-1} = A^{-1} \cdot A = I$,
  where $I$ is the **identity matrix** (a matrix with 1’s on the diagonal and 0’s elsewhere).

Such a matrix is called **non-singular** (invertible).

### 🔁 Left and Right Multiplication

* **Left inverse:** $A^{-1} A = I$
* **Right inverse:** $A A^{-1} = I$

If both hold true, the matrix is **invertible**.

---

## ❌ **2. Singular Matrix (Non-invertible)**

A **singular matrix** is one **that does not have an inverse**.

### Example:

Let

$$
A = \begin{bmatrix} 2 & 4 \\ 1 & 2 \end{bmatrix}
$$

### 🧮 Determinant Check:

$$
\text{det}(A) = (2)(2) - (4)(1) = 4 - 4 = 0
$$

Since the **determinant is 0**, **A is singular** and **non-invertible**.

### 🔄 Why determinant 0 means no inverse?

* A zero determinant means the matrix **collapses space**—it squashes some dimensions together (no longer full rank).
* It cannot be reversed because **information is lost**.

---

### 🧲 **Alternative Reason (Zero Product)**

Suppose we can find a **non-zero vector $x$** such that:

$$
A \cdot x = 0
$$

This implies that **matrix A maps a non-zero vector to the zero vector**, which means:

* The transformation is **not injective** (not one-to-one)
* Some directions are being **flattened**, i.e., A is not invertible

#### Example:

Take the matrix

$$
A = \begin{bmatrix} 2 & 4 \\ 1 & 2 \end{bmatrix}
$$

Let

$$
x = \begin{bmatrix} 2 \\ -1 \end{bmatrix}
$$

Then:

$$
A \cdot x = \begin{bmatrix} 2×2 + 4×(-1) \\ 1×2 + 2×(-1) \end{bmatrix} = \begin{bmatrix} 4 - 4 \\ 2 - 2 \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \end{bmatrix}
$$

So matrix A maps a non-zero vector to 0 — again confirming it is **not invertible**.

---

## 📘 **3. Gauss-Jordan Elimination and Matrix Inverse**

Gauss-Jordan elimination is a technique for solving **systems of linear equations**, often represented as:

$$
AX = B
$$

To solve this, you can **transform** the augmented matrix $[A \,|\, B]$ into reduced row-echelon form (RREF).

### 💡 How it's related to matrix inverse:

To find the inverse of matrix A, you augment it with the identity matrix:

$$
[A \,|\, I]
$$

Then use **row operations** to convert A into the identity matrix:

$$
[I \,|\, A^{-1}]
$$

This process works **only if A is invertible**. If not, the row reduction will fail to produce an identity on the left side.

### Example: Inverting with Gauss-Jordan

Let

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

Form the augmented matrix:

$$
[A \,|\, I] = \begin{bmatrix} 1 & 2 & | & 1 & 0 \\ 3 & 4 & | & 0 & 1 \end{bmatrix}
$$

Using row operations, we reduce this to:

$$
[I \,|\, A^{-1}] = \begin{bmatrix} 1 & 0 & | & -2 & 1 \\ 0 & 1 & | & 1.5 & -0.5 \end{bmatrix}
$$

So the inverse is

$$
A^{-1} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}
$$

---

## 🔁 **Summary**

| Concept                              | Description                                                       | 
| ------------------------------------ | ----------------------------------------------------------------- |
| **Invertible Matrix (Non-singular)** | Square matrix with a two-sided inverse: $A A^{-1} = A^{-1} A = I$ |                                   
| **Singular Matrix**                  | No inverse; determinant is 0 or it maps non-zero vectors to zero  |                                   
| **Det = 0**                          | Matrix is not full-rank; space is collapsed                       |                                   
| **Zero Mapping**                     | If $A x = 0$ for non-zero $x$, A is not invertible                |                                   
| **Gauss-Jordan Method**              | Row-reduces (\[A I]) to find $A^{-1}$ if it exists                |


In [6]:
A = np.array([[2, 4],
              [1, 2]])

# Compute determinant
det = np.linalg.det(A)
print("Determinant of A:", det)

if det == 0:
    print("Matrix A is singular (non-invertible).")
else:
    print("Matrix A is invertible.")


Determinant of A: 0.0
Matrix A is singular (non-invertible).


In [7]:
x = np.array([[2], [-1]])  # Try a candidate vector

result = A @ x
print("A @ x =\n", result)

if np.all(result == 0):
    print("Matrix A maps a non-zero vector to zero → A is singular.")

A @ x =
 [[0]
 [0]]
Matrix A maps a non-zero vector to zero → A is singular.


In [8]:
try:
    A_inv = np.linalg.inv(A)
    print("Inverse of A:\n", A_inv)
except np.linalg.LinAlgError:
    print("Cannot compute inverse — matrix is singular.")

Cannot compute inverse — matrix is singular.


In [9]:
# Example invertible matrix
A = np.array([[1., 2.],
              [3., 4.]])
n = A.shape[0]
augmented = np.hstack((A, np.identity(n)))

# Gauss-Jordan elimination
for i in range(n):
    # Make the diagonal element 1
    factor = augmented[i, i]
    augmented[i] = augmented[i] / factor
    
    # Eliminate other rows
    for j in range(n):
        if i != j:
            row_factor = augmented[j, i]
            augmented[j] -= row_factor * augmented[i]

A_inverse = augmented[:, n:]

print("Gauss-Jordan computed inverse of A:\n", A_inverse)

# Verify
print("A @ A_inverse =\n", A @ A_inverse)


Gauss-Jordan computed inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ A_inverse =
 [[1. 0.]
 [0. 1.]]
