In [2]:
import numpy as np

# **Permutation Matrices**

Permutation matrices reorder the rows of a matrix.
If we multiply a matrix (A) on the **left** by a permutation matrix (P):

$$
PA = \text{row-permuted } A
$$

Example: Swap row 1 and row 2 of a 3×3 matrix.

$
P = \begin{bmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1
\end{bmatrix}
$


In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

P = np.array([[0, 1, 0],
              [1, 0, 0],
              [0, 0, 1]])

print("PA =\n", P @ A)

PA =
 [[4 5 6]
 [1 2 3]
 [7 8 9]]


---

# **LU Factorization With Pivoting**

Without pivoting, we write:

$$
A = LU
$$

But if a pivot is **zero** or **very small**, Gaussian elimination becomes unstable.
To fix this, we **swap rows first**, using a permutation matrix (P):

$$
PA = LU
$$

* (P) reorders rows to place a good (nonzero) pivot on top.
* (L) is lower-triangular.
* (U) is upper-triangular.

This decomposition is called **LU with partial pivoting**.

---

In [3]:
from scipy.linalg import lu

In [4]:
# (LU with pivoting)
# Using SciPy for convenience:

A = np.array([[0., 2., 1.],
              [3., 4., 5.],
              [6., 7., 8.]])

P, L, U = lu(A)

print("P =\n", P)
print("L =\n", L)
print("U =\n", U)

# Check PA = LU
print("PA =\n", P @ A)
print("LU =\n", L @ U)

# The first row pivot is 0, so LU automatically swaps rows using (P).


P =
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L =
 [[1.   0.   0.  ]
 [0.   1.   0.  ]
 [0.5  0.25 1.  ]]
U =
 [[6.   7.   8.  ]
 [0.   2.   1.  ]
 [0.   0.   0.75]]
PA =
 [[3. 4. 5.]
 [6. 7. 8.]
 [0. 2. 1.]]
LU =
 [[6. 7. 8.]
 [0. 2. 1.]
 [3. 4. 5.]]


---

# **Concept 3 — Matrix Transpose**

The transpose of a matrix (A) is denoted (A^T).
You obtain it by **exchanging rows and columns**:

$$
(A^T)*{ij} = A*{ji}
$$

Example: A 3×2 matrix

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
\quad\Rightarrow\quad
A^T =
\begin{bmatrix}
1 & 3 & 5 \\
2 & 4 & 6
\end{bmatrix}
$$

In [5]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("A^T =\n", A.T)

A^T =
 [[1 3 5]
 [2 4 6]]


---

# **Symmetric Matrices**

A matrix is **symmetric** if:

$$
A^T = A
$$

Example:

$$
A =
\begin{bmatrix}
2 & 5 \\
5 & 7
\end{bmatrix}
$$

It equals its own transpose.

---

In [3]:
A = np.array([[2, 5],
              [5, 7]])

print("Symmetric?", np.allclose(A, A.T))

Symmetric? True


# **Concept 5 — (R^T R) Is Always Symmetric**

For any real matrix (R) (even rectangular), the product $R^T R$ is always symmetric.

Example: (R) is 3×2

$$
R = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
$$

Compute:

$$
R^T R =
\begin{bmatrix}
35 & 44 \\
44 & 56
\end{bmatrix}
$$

Which is symmetric.

---


In [4]:
R = np.array([[1, 2],
              [3, 4],
              [5, 6]])

M = R.T @ R
print(M)
print("Symmetric?", np.allclose(M, M.T))

[[35 44]
 [44 56]]
Symmetric? True


---

# **Vector Spaces**

A vector space is a set of vectors closed under:

1. **Vector addition**
2. **Scalar multiplication**

Examples:

* $ \mathbb{R}^2 $: all ordered pairs ((x, y))
* $ \mathbb{R}^3 $: all triples ((x, y, z))
* $ \mathbb{R}^n $: all n-tuples

### Why do we need the zero vector?

Because:

* It acts as the **additive identity**
* Subspaces must contain it
* Without the zero vector, you cannot satisfy closure under scalar multiplication (e.g., multiply any vector by 0 gives the zero vector)

---

In [5]:
# two vectors in R^2
v = np.array([2, 3])
w = np.array([-1, 4])

# closure under addition
print("v + w =", v + w)

# closure under scalar multiplication
print("3 * v =", 3 * v)
print("0 * v =", 0 * v)  # zero vector appears

v + w = [1 7]
3 * v = [6 9]
0 * v = [0 0]


---

# **Concept 7 — Subspaces of $ \mathbb{R}^2 $**

A **subspace** is a subset of a vector space that is itself a vector space.

Subspaces of $ \mathbb{R}^2 $:

1. **{0}** (just the zero vector)
2. **Any line through the origin**
3. **All of $ \mathbb{R}^2 $**

Key rule:
A line is a subspace **only** if it passes through the origin.

Example line subspace:
All multiples of the vector ( (2, 1) ):

$$
\text{Span}{(2,1)}
= {\alpha (2, 1) : \alpha \in \mathbb{R}}
$$

---

In [6]:
v = np.array([2, 1])

# generate some points in the subspace
points = [a * v for a in [-2, -1, 0, 1, 2]]
print(points)

[array([-4, -2]), array([-2, -1]), array([0, 0]), array([2, 1]), array([4, 2])]


---

# **Subspaces of $ \mathbb{R}^3 $**

The subspaces of $ \mathbb{R}^3 $ are:

1. **{0}**
2. **Lines through the origin**
3. **Planes through the origin**
4. **All of ( \mathbb{R}^3 )**

So it’s the same pattern as before, but with one more dimension.

---

### ✔ Python Example — Plane subspace in $ \mathbb{R}^3 $

A plane through the origin can be described as the span of two independent vectors.

Example:

$$
\text{Span}{(1, 0, 0), (0, 1, 1)}
$$

In [7]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 1])

# random linear combinations
for a, b in [(1,2), (-1,3), (0,0)]:
    print(a * v1 + b * v2)

[1 2 2]
[-1  3  3]
[0 0 0]


---

# **Column Space of a Matrix**

If you have a matrix (A), its **column space** is:

$$
\text{Col}(A) = \text{all linear combinations of its columns}
$$

If (A) is a **3×2** matrix:

* Each column is a vector in **( \mathbb{R}^3 )**
* All linear combinations form a **subspace of ( \mathbb{R}^3 )**

Let

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 6 \\
4 & 8
\end{bmatrix}
$$

Columns:

$$
v_1 = \begin{bmatrix} 1 \ 3 \ 4 \end{bmatrix},\quad
v_2 = \begin{bmatrix} 2 \ 6 \ 8 \end{bmatrix}
$$

But notice:

$$
v_2 = 2 v_1
$$

So the column space is all multiples of (v_1):
→ **A line in $ \mathbb{R}^3 $**

If instead the columns were independent, they'd span a **plane**.

---

In [8]:
A = np.array([[1, 2],
              [3, 6],
              [4, 8]])   # columns are multiples

v1 = A[:, 0]
v2 = A[:, 1]

print("v2 is 2 * v1:", np.allclose(v2, 2*v1))

# generate some points in the column space
for a in [-2, -1, 0, 1, 3]:
    print(a * v1)


# If the columns had been independent:

B = np.array([[1, 0],
              [0, 1],
              [0, 1]])

# random combinations
for a, b in [(1,2), (-1,3), (0,0)]:
    print(a*B[:,0] + b*B[:,1])


# This spans a **plane**.


v2 is 2 * v1: True
[-2 -6 -8]
[-1 -3 -4]
[0 0 0]
[1 3 4]
[ 3  9 12]
[1 2 2]
[-1  3  3]
[0 0 0]


---

# **All combinations of two vectors form a plane $in ( \mathbb{R}^3 )$**

Let two vectors in $ \mathbb{R}^3 $ be:

$$
v_1 = \begin{bmatrix}1\\0\\0\end{bmatrix},\quad
v_2 = \begin{bmatrix}1\\1\\0\end{bmatrix}
$$

Their linear combinations are:

$$
a v_1 + b v_2 = \begin{bmatrix} a + b \ b \ 0 \end{bmatrix}
$$

This describes the entire **(xy)-plane** inside $ \mathbb{R}^3 $.

General fact:

$$
\text{Span}(v_1, v_2) = \text{Plane through the origin}
$$
as long as (v_1) and (v_2) are **not multiples** of each other.

---

In [9]:
v1 = np.array([1, 0, 0])
v2 = np.array([1, 1, 0])

# generate points in the plane
for a, b in [(1,2), (-1,3), (0,0), (2,-1)]:
    print(a*v1 + b*v2)

[3 2 0]
[2 3 0]
[0 0 0]
[ 1 -1  0]
